<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AwardsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('awards')->delete();
        
        \DB::table('awards')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'Latin America Firm',
                'award_type_id' => 1,
                'text' => '<p>Pelo segundo ano consecutivo, recebemos o prêmio mais importante do Chambers Latin America Awards 2020: melhor escritório de advocacia da América Latina.</p>',
                'text_en' => NULL,
                'created_at' => '2021-08-09 15:18:37',
                'updated_at' => '2021-08-09 15:18:37',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'Brazil Firm',
                'award_type_id' => 1,
            'text' => '<p>De forma inédita, o Chambers Latin America Awards 2019 concedeu a um único escritório os dois principais prêmios (nacional e regional).</p>',
                'text_en' => NULL,
                'created_at' => '2021-08-09 15:19:32',
                'updated_at' => '2021-08-09 15:19:32',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'Top Ranked Firm',
                'award_type_id' => 2,
            'text' => '<p>Tivemos o maior número de áreas reconhecidas (23) e práticas Band 1 (13), além do maior número de reconhecimentos individuais totais (67), dentre os quais 12 Band 1, um Eminent Practitioner e um Star Individual.</p>',
                'text_en' => NULL,
                'created_at' => '2021-08-09 15:21:45',
                'updated_at' => '2021-08-09 15:21:45',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'title' => '1st Tier Firm ',
                'award_type_id' => 3,
            'text' => '<p>Segundo o guia inglês The Legal 500 Latin America 2021, que elege os escritórios e advogados mais importantes da região, temos o maior número de áreas reconhecidas (32), o maior número de áreas Tier 1 (15) e o maior número de reconhecimentos individuais na categoria mais alta - <em>Leading Individual (17).</em></p>',
                'text_en' => NULL,
                'created_at' => '2021-08-09 15:22:33',
                'updated_at' => '2021-08-09 15:22:33',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'Brazil Law Firm of the Year',
                'award_type_id' => 4,
                'text' => '<p>A edição 2019 do guia Who\'s Who Legal Brazil apresentou <strong>59 reconhecimentos</strong> aos nossos profissionais entre <strong>27 práticas</strong> do Direito.</p>',
                'text_en' => NULL,
                'created_at' => '2021-08-09 15:24:14',
                'updated_at' => '2021-08-09 15:24:14',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'Brazil Law Firm of the Year',
                'award_type_id' => 5,
                'text' => '<p>Fomos eleitos como o melhor escritório brasileiro pela publicação americana LatinFinance. A edição 2020 dos Deals of the Year Awards, reconhece as operações e instituições mais importantes do ano. Além disso, estamos honrados por atuar em quatro operações que também foram premiadas nas <strong>Structured Financing Deal of the Year, Equity Follow-On Deal of the Year, Cross-Border M&amp;A Deal of the Year e Domestic M&amp;A Deal of the Year.</strong></p>',
                'text_en' => NULL,
                'created_at' => '2021-08-09 15:30:26',
                'updated_at' => '2021-08-09 15:30:26',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'title' => 'Elite Law Firm in Latin America',
                'award_type_id' => 6,
                'text' => '<p>Fomos eleitos um dos escritórios mais relevantes da América Latina, segundo o relatório Latin Lawyer Elite 2021.</p>',
                'text_en' => NULL,
                'created_at' => '2021-08-09 15:31:17',
                'updated_at' => '2021-08-09 15:31:17',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'Brazil Firm of the Year',
                'award_type_id' => 7,
                'text' => '<p>Recebemos três prêmios no <strong>IFLR Americas Awards 2021</strong>, dentre eles o mais importante em âmbito nacional: Brazil Firm of the Year. Também ganhamos na categoria Brazil Corporate Firm of the Year.</p>',
                'text_en' => NULL,
                'created_at' => '2021-08-09 15:33:37',
                'updated_at' => '2021-08-09 15:33:37',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'title' => 'South American Firm of the Year ',
                'award_type_id' => 7,
                'text' => '<p>Em sua 13ª edição, tivemos a felicidade de celebrar a conquista de quatro categorias: South American Firm of the Year; Most Innovative Firm of the Year, Capital Markets Firm of the Year e Reestructuring Deal of the Year.</p>',
                'text_en' => NULL,
                'created_at' => '2021-08-09 15:34:29',
                'updated_at' => '2021-08-09 15:34:29',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'title' => 'Recognized Firm',
                'award_type_id' => 8,
                'text' => '<p>Fomos reconhecidos como um dos escritórios <strong>mais relevantes da América Latina </strong>no guia anual 250 da publicação inglesa Latin Lawyer, sendo destacados em 27 áreas e recebemos 136 reconhecimentos individuais</p>',
                'text_en' => NULL,
                'created_at' => '2021-08-09 15:48:49',
                'updated_at' => '2021-08-09 15:48:49',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'title' => '1st Tier Firm',
                'award_type_id' => 9,
            'text' => '<p>O guia inglês IFLR1000 nos reconheceu como Tier 1 em todas as áreas analisadas: Banking, Capital Markets: Debt e Equity, M&amp;A, Private Equity, Project Development e Project Finance (promovida neste ano) Na trigésima edição, ainda recebemos o maior número de reconhecimentos individuais nas mais altas colocações.</p>',
                'text_en' => NULL,
                'created_at' => '2021-08-09 15:49:28',
                'updated_at' => '2021-08-09 15:49:28',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'title' => 'Aviation Finance',
                'award_type_id' => 1,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:51',
                'updated_at' => '2021-08-16 18:10:51',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'title' => 'Corporate and M&A - Eminent Practitioner',
                'award_type_id' => 1,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:51',
                'updated_at' => '2021-08-16 18:10:51',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'title' => 'Environment',
                'award_type_id' => 1,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:51',
                'updated_at' => '2021-08-16 18:10:51',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'title' => 'Private Funds',
                'award_type_id' => 10,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:51',
                'updated_at' => '2021-08-16 18:10:51',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'title' => 'Tax',
                'award_type_id' => 3,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:52',
                'updated_at' => '2021-08-16 18:10:52',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'title' => 'Bankruptcy/Restructuring  ',
                'award_type_id' => 11,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:52',
                'updated_at' => '2021-08-16 18:10:52',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'title' => 'Pro Bono',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:52',
                'updated_at' => '2021-08-16 18:10:52',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'title' => 'Environment',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:52',
                'updated_at' => '2021-08-16 18:10:52',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'title' => 'Technology',
                'award_type_id' => 1,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:52',
                'updated_at' => '2021-08-16 18:10:52',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'title' => 'Life Sciences - Band 1',
                'award_type_id' => 1,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:52',
                'updated_at' => '2021-08-16 18:10:52',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'title' => 'Environment - Band 1  ',
                'award_type_id' => 1,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:52',
                'updated_at' => '2021-08-16 18:10:52',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'title' => 'Corporate/M&A ',
                'award_type_id' => 1,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:52',
                'updated_at' => '2021-08-16 18:10:52',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'title' => 'Maritime  ',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:52',
                'updated_at' => '2021-08-16 18:10:52',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'title' => 'Banking & Finance: Regulatory - Star individual',
                'award_type_id' => 1,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:52',
                'updated_at' => '2021-08-16 18:10:52',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'title' => 'Investment Funds',
                'award_type_id' => 1,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:52',
                'updated_at' => '2021-08-16 18:10:52',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'title' => 'Corporate/M&A - Band 1  ',
                'award_type_id' => 1,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:52',
                'updated_at' => '2021-08-16 18:10:52',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'title' => 'Energy & Natural Resources: Mining - Band 1  ',
                'award_type_id' => 1,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:52',
                'updated_at' => '2021-08-16 18:10:52',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'title' => 'Tax',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:52',
                'updated_at' => '2021-08-16 18:10:52',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'title' => 'Dispute Resolution: Litigation',
                'award_type_id' => 11,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:52',
                'updated_at' => '2021-08-16 18:10:52',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'title' => 'TMT: Cybersecurity and Data Privacy',
                'award_type_id' => 3,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:52',
                'updated_at' => '2021-08-16 18:10:52',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'title' => 'Competition/Antitrust - Band 1',
                'award_type_id' => 11,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:52',
                'updated_at' => '2021-08-16 18:10:52',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'title' => 'Compliance / Competition and Antitrust',
                'award_type_id' => 3,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:52',
                'updated_at' => '2021-08-16 18:10:52',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'title' => 'Insurance',
                'award_type_id' => 1,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:52',
                'updated_at' => '2021-08-16 18:10:52',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'title' => 'Private Equity',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:52',
                'updated_at' => '2021-08-16 18:10:52',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'title' => 'Dispute Resolution: Litigation',
                'award_type_id' => 3,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:52',
                'updated_at' => '2021-08-16 18:10:52',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'title' => 'Energy and Natural Resources: Hydrocarbons',
                'award_type_id' => 3,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:52',
                'updated_at' => '2021-08-16 18:10:52',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 39,
                'title' => 'Banking & Finance: Regulatory',
                'award_type_id' => 1,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:52',
                'updated_at' => '2021-08-16 18:10:52',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 40,
                'title' => 'Banking & Finance',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:52',
                'updated_at' => '2021-08-16 18:10:52',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 41,
                'title' => 'Capital Markets',
                'award_type_id' => 1,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 42,
                'title' => 'Corporate and M&A',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 43,
                'title' => 'Energy',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 44,
                'title' => 'Real Estate',
                'award_type_id' => 1,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 45,
                'title' => 'Tax: Litigation',
                'award_type_id' => 11,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 46,
                'title' => 'Dispute Resolution: Arbitration / Litigation',
                'award_type_id' => 11,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 47,
                'title' => 'Bankruptcy/Restructuring - Band 1',
                'award_type_id' => 11,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 48,
                'title' => 'Corporate and M&A / Management',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 49,
                'title' => 'Corporate and M&A',
                'award_type_id' => 3,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 50,
                'title' => 'Competition/Antitrust',
                'award_type_id' => 11,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 51,
                'title' => 'Corporate and M&A / Banking & Finance / Capital Markets / Project Finance & Infrastructure / Pro Bono',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 52,
                'title' => 'Banking & Finance',
                'award_type_id' => 1,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 53,
                'title' => 'Intellectual Property',
                'award_type_id' => 11,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 54,
                'title' => 'Energy & Natural Resources: Power',
                'award_type_id' => 1,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 55,
                'title' => 'Projects',
                'award_type_id' => 1,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 56,
                'title' => 'Data, Technology and Privacy Law',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 57,
                'title' => 'Tax - Band 1',
                'award_type_id' => 1,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 58,
                'title' => 'Real Estate / Real Estate: Finance',
                'award_type_id' => 1,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 59,
                'title' => 'Labour & Employment',
                'award_type_id' => 11,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 60,
                'title' => 'City Focus - Brasília - Tax',
                'award_type_id' => 3,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 61,
                'title' => 'Tax',
                'award_type_id' => 1,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 62,
                'title' => 'Management / Administrative Law',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 63,
                'title' => 'Litigation',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 64,
                'title' => 'Management',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 65,
                'title' => 'Capital markets: Equity / M&A',
                'award_type_id' => 9,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 66,
                'title' => 'Insurance',
                'award_type_id' => 3,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 67,
                'title' => 'Dispute Resolution: White-Collar Crime',
                'award_type_id' => 11,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 68,
                'title' => 'Labour',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 69,
                'title' => 'International Trade/WTO',
                'award_type_id' => 11,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:53',
                'updated_at' => '2021-08-16 18:10:53',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 70,
                'title' => 'Consumer Law - Band 1',
                'award_type_id' => 11,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:54',
                'updated_at' => '2021-08-16 18:10:54',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 71,
                'title' => 'Energy and Natural Resources: Hydrocarbons - Rising Star',
                'award_type_id' => 3,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:54',
                'updated_at' => '2021-08-16 18:10:54',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 72,
                'title' => 'Dispute Resolution: Arbitration',
                'award_type_id' => 11,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:54',
                'updated_at' => '2021-08-16 18:10:54',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 73,
                'title' => 'Competition/Antitrust / International Trade/WTO - Band 1',
                'award_type_id' => 11,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:54',
                'updated_at' => '2021-08-16 18:10:54',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 74,
                'title' => 'Administrative Law / Anti-corruption Investigations and Compliance',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:54',
                'updated_at' => '2021-08-16 18:10:54',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 75,
                'title' => 'Antitrust & Competition / Litigation',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:54',
                'updated_at' => '2021-08-16 18:10:54',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 76,
                'title' => 'Insurance & Reinsurance',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:54',
                'updated_at' => '2021-08-16 18:10:54',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 77,
                'title' => 'Agribusiness / Capital Markets',
                'award_type_id' => 1,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:54',
                'updated_at' => '2021-08-16 18:10:54',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 78,
                'title' => 'Corporate and M&A – Recommended',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:54',
                'updated_at' => '2021-08-16 18:10:54',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 79,
                'title' => 'Banking & Finance / Project Finance & Infrastructure',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:10:54',
                'updated_at' => '2021-08-16 18:10:54',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 80,
                'title' => 'Aviation',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:40',
                'updated_at' => '2021-08-16 18:32:40',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 81,
                'title' => 'Management / Corporate and M&A',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:40',
                'updated_at' => '2021-08-16 18:32:40',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 82,
                'title' => 'M&A',
                'award_type_id' => 9,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:40',
                'updated_at' => '2021-08-16 18:32:40',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 83,
                'title' => 'Restructuring & insolvency',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:40',
                'updated_at' => '2021-08-16 18:32:40',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 84,
                'title' => 'Environment',
                'award_type_id' => 3,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:40',
                'updated_at' => '2021-08-16 18:32:40',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 85,
                'title' => 'Litigation / Data, Technology and Privacy Law',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:40',
                'updated_at' => '2021-08-16 18:32:40',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 86,
                'title' => 'Life Sciences',
                'award_type_id' => 3,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:40',
                'updated_at' => '2021-08-16 18:32:40',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 87,
                'title' => 'Commercial',
                'award_type_id' => 12,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:40',
                'updated_at' => '2021-08-16 18:32:40',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 88,
                'title' => 'Fintech Legal - Band 1',
                'award_type_id' => 13,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:40',
                'updated_at' => '2021-08-16 18:32:40',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 89,
                'title' => 'Investment Funds',
                'award_type_id' => 14,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:40',
                'updated_at' => '2021-08-16 18:32:40',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 90,
                'title' => 'Corporate and M&A / Private Wealth',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:40',
                'updated_at' => '2021-08-16 18:32:40',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 91,
                'title' => 'Mining & Metals',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:40',
                'updated_at' => '2021-08-16 18:32:40',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 92,
                'title' => 'Litigation / Arbitration / Administrative law',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:40',
                'updated_at' => '2021-08-16 18:32:40',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 93,
                'title' => 'Data',
                'award_type_id' => 15,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 94,
                'title' => 'Antitrust & Competition / Pro Bono',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 95,
                'title' => 'Antitrust & Competition',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 96,
                'title' => 'Insurance & Reinsurance / Insurance',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 97,
                'title' => 'Tax',
                'award_type_id' => 16,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 98,
                'title' => 'Tax',
                'award_type_id' => 17,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 99,
                'title' => 'Project finance & Infrastructure',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 100,
                'title' => 'Corporate and M&A / Private  Equity / Banking & Finance / Corporate Governance',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 101,
                'title' => 'Fintech Legal',
                'award_type_id' => 13,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 102,
                'title' => 'Banking and Finance',
                'award_type_id' => 3,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 103,
                'title' => 'Capital Markets / Corporate and M&A',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 104,
                'title' => 'Real Estate & Tourism',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 105,
                'title' => 'Private Wealth Law',
                'award_type_id' => 18,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 106,
                'title' => 'Arbitration / Litigation',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 107,
                'title' => 'Restructuring & Insolvency / Management',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 108,
                'title' => 'Corporate and M&A / Capital Markets',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 109,
                'title' => 'Corporate and M&A / Private Equity',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id' => 110,
                'title' => 'Banking and Finance / M&A',
                'award_type_id' => 9,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id' => 111,
                'title' => 'Antitrust & Competition / Anti-corruption investigations and compliance',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id' => 112,
                'title' => 'Capital Markets',
                'award_type_id' => 17,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            111 => 
            array (
                'id' => 113,
                'title' => 'Corporate and M&A / Banking & Finance / Capital Markets',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            112 => 
            array (
                'id' => 114,
                'title' => 'Data, Technology and Privacy Law / Intellectual Property',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            113 => 
            array (
                'id' => 115,
                'title' => 'Electricity',
                'award_type_id' => 3,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            114 => 
            array (
                'id' => 116,
                'title' => 'Project Finance & Infrastructure / Arbitration',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            115 => 
            array (
                'id' => 117,
                'title' => 'TMT: Cybersecurity and Data Privacy / Tech, Innovation and Digital Business',
                'award_type_id' => 3,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            116 => 
            array (
                'id' => 118,
                'title' => 'Banking and Finance / Capital Markets',
                'award_type_id' => 9,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            117 => 
            array (
                'id' => 119,
                'title' => 'Dispute Resolution: Litigation / Transport and shipping',
                'award_type_id' => 3,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            118 => 
            array (
                'id' => 120,
                'title' => 'Restructuring & Insolvency / Litigation',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:41',
                'updated_at' => '2021-08-16 18:32:41',
                'deleted_at' => NULL,
            ),
            119 => 
            array (
                'id' => 121,
                'title' => 'Public Law',
                'award_type_id' => 3,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:42',
                'updated_at' => '2021-08-16 18:32:42',
                'deleted_at' => NULL,
            ),
            120 => 
            array (
                'id' => 122,
                'title' => 'Energy and Natural Resources: Hydrocarbons / Transport and Shipping',
                'award_type_id' => 3,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:42',
                'updated_at' => '2021-08-16 18:32:42',
                'deleted_at' => NULL,
            ),
            121 => 
            array (
                'id' => 123,
                'title' => 'Energy / Project Finance & Infrastructure / Corporate and M&A',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:42',
                'updated_at' => '2021-08-16 18:32:42',
                'deleted_at' => NULL,
            ),
            122 => 
            array (
                'id' => 124,
                'title' => 'Intellectual Property   ',
                'award_type_id' => 14,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:42',
                'updated_at' => '2021-08-16 18:32:42',
                'deleted_at' => NULL,
            ),
            123 => 
            array (
                'id' => 125,
                'title' => 'Wealth and Succession Planning',
                'award_type_id' => 3,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:42',
                'updated_at' => '2021-08-16 18:32:42',
                'deleted_at' => NULL,
            ),
            124 => 
            array (
                'id' => 126,
                'title' => 'Anti-corruption Investigations and Compliance',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:42',
                'updated_at' => '2021-08-16 18:32:42',
                'deleted_at' => NULL,
            ),
            125 => 
            array (
                'id' => 127,
                'title' => 'Labour and Employment',
                'award_type_id' => 3,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:42',
                'updated_at' => '2021-08-16 18:32:42',
                'deleted_at' => NULL,
            ),
            126 => 
            array (
                'id' => 128,
                'title' => 'Trade / Tax',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:42',
                'updated_at' => '2021-08-16 18:32:42',
                'deleted_at' => NULL,
            ),
            127 => 
            array (
                'id' => 129,
                'title' => 'Private Wealth',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:42',
                'updated_at' => '2021-08-16 18:32:42',
                'deleted_at' => NULL,
            ),
            128 => 
            array (
                'id' => 130,
                'title' => 'Management / Corporate and M&A / Data, Technology and Privacy Law / Telecoms & Media',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:42',
                'updated_at' => '2021-08-16 18:32:42',
                'deleted_at' => NULL,
            ),
            129 => 
            array (
                'id' => 131,
                'title' => 'Arbitration',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:42',
                'updated_at' => '2021-08-16 18:32:42',
                'deleted_at' => NULL,
            ),
            130 => 
            array (
                'id' => 132,
                'title' => 'Management / Antitrust & Competition / Trade',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:42',
                'updated_at' => '2021-08-16 18:32:42',
                'deleted_at' => NULL,
            ),
            131 => 
            array (
                'id' => 133,
                'title' => 'Winner Brazil',
                'award_type_id' => 19,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:42',
                'updated_at' => '2021-08-16 18:32:42',
                'deleted_at' => NULL,
            ),
            132 => 
            array (
                'id' => 134,
                'title' => 'Corporate and M&A / Project Finance & Infrastructure / Energy / Maritime',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:42',
                'updated_at' => '2021-08-16 18:32:42',
                'deleted_at' => NULL,
            ),
            133 => 
            array (
                'id' => 135,
                'title' => 'Management / Tax',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:42',
                'updated_at' => '2021-08-16 18:32:42',
                'deleted_at' => NULL,
            ),
            134 => 
            array (
                'id' => 136,
                'title' => 'Compliance / Public Law',
                'award_type_id' => 3,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:42',
                'updated_at' => '2021-08-16 18:32:42',
                'deleted_at' => NULL,
            ),
            135 => 
            array (
                'id' => 137,
                'title' => 'Capital Markets / Project Finance & Infrastructure',
                'award_type_id' => 8,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:42',
                'updated_at' => '2021-08-16 18:32:42',
                'deleted_at' => NULL,
            ),
            136 => 
            array (
                'id' => 138,
                'title' => 'Competition and Antitrust / Dispute Resolution: Arbitration / Litigation',
                'award_type_id' => 3,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:42',
                'updated_at' => '2021-08-16 18:32:42',
                'deleted_at' => NULL,
            ),
            137 => 
            array (
                'id' => 139,
                'title' => 'Tax  - Leading Individual',
                'award_type_id' => 3,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:42',
                'updated_at' => '2021-08-16 18:32:42',
                'deleted_at' => NULL,
            ),
            138 => 
            array (
                'id' => 140,
                'title' => 'Life Sciences / Product Liability Defence',
                'award_type_id' => 10,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:42',
                'updated_at' => '2021-08-16 18:32:42',
                'deleted_at' => NULL,
            ),
            139 => 
            array (
                'id' => 141,
                'title' => 'Insurance / Life Sciences',
                'award_type_id' => 3,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:43',
                'updated_at' => '2021-08-16 18:32:43',
                'deleted_at' => NULL,
            ),
            140 => 
            array (
                'id' => 142,
                'title' => 'Restructuring and Insolvency - Rising Star',
                'award_type_id' => 3,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:43',
                'updated_at' => '2021-08-16 18:32:43',
                'deleted_at' => NULL,
            ),
            141 => 
            array (
                'id' => 143,
                'title' => 'City Focus - Brasília: Litigation / Compliance /White-Collar Crime and Investigations',
                'award_type_id' => 3,
                'text' => NULL,
                'text_en' => NULL,
                'created_at' => '2021-08-16 18:32:43',
                'updated_at' => '2021-08-16 18:32:43',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}