<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CallsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('calls')->delete();
        
        \DB::table('calls')->insert(array (
            0 => 
            array (
                'id' => 1,
                'page_id' => 1,
                'sub_page_id' => NULL,
                'image' => '1629226822.png',
                'title' => 'Atuação',
                'title_en' => 'Atuação',
                'text' => '<p>Somos um escritório de advocacia com visão global e advogados especialistas em mais de 40 práticas do Direito.</p>',
                'text_en' => '<p></p>',
                'link' => '',
                'text_link' => 'Ver áreas de atuação',
                'text_link_en' => 'Ver áreas de atuação',
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-08-17 19:17:22',
                'deleted_at' => '2021-06-30 19:54:19',
            ),
            1 => 
            array (
                'id' => 2,
                'page_id' => 1,
                'sub_page_id' => NULL,
                'image' => NULL,
                'title' => 'Conhecimento Jurídico',
                'title_en' => 'Conhecimento Jurídico',
                'text' => '<p>O que você precisa saber para estar à frente em relação às mudanças da lei.</p>',
                'text_en' => '<p></p>',
                'link' => NULL,
                'text_link' => 'Ver todos',
                'text_link_en' => 'Ver todos',
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-08-17 19:18:26',
                'deleted_at' => '2021-07-01 20:06:06',
            ),
            2 => 
            array (
                'id' => 3,
                'page_id' => 1,
                'sub_page_id' => NULL,
                'image' => '1629226853.png',
                'title' => 'Eventos',
                'title_en' => 'Eventos',
                'text' => '<p></p>',
                'text_en' => '<p></p>',
                'link' => NULL,
                'text_link' => 'Ver todos',
                'text_link_en' => 'Ver todos',
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-08-17 16:00:53',
                'deleted_at' => '2021-07-01 20:06:06',
            ),
            3 => 
            array (
                'id' => 4,
                'page_id' => 1,
                'sub_page_id' => NULL,
                'image' => NULL,
                'title' => 'Responsabilidade Social',
                'title_en' => 'Responsabilidade Social',
                'text' => '<p></p>',
                'text_en' => '<p></p>',
                'link' => NULL,
                'text_link' => 'Ver todos',
                'text_link_en' => 'Ver todos',
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-07-01 18:38:05',
                'deleted_at' => '2021-07-01 20:06:06',
            ),
            4 => 
            array (
                'id' => 5,
                'page_id' => 1,
                'sub_page_id' => NULL,
                'image' => '1629226914.png',
                'title' => 'Programa de Estágio',
                'title_en' => 'Programa de Estágio',
                'text' => '<p>Acreditamos que nossos talentos constroem o nosso negócio. Desenvolvemos profissionais, mas também pessoas capazes de lidar com os desafios do mundo atual.</p>',
                'text_en' => '<p></p>',
                'link' => NULL,
                'text_link' => 'Conheça o programa',
                'text_link_en' => 'Conheça o programa',
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-08-17 19:18:44',
                'deleted_at' => '2021-07-01 20:06:06',
            ),
            5 => 
            array (
                'id' => 6,
                'page_id' => 1,
                'sub_page_id' => NULL,
                'image' => NULL,
                'title' => 'Reconhecimentos do Escritório',
                'title_en' => 'Reconhecimentos do Escritório',
                'text' => '<p>Conheça nossos principais destaques na publicações nacionais e internacionais mais relevantes.</p>',
                'text_en' => '<p></p>',
                'link' => NULL,
                'text_link' => 'Ver todos',
                'text_link_en' => 'Ver todos',
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-08-17 19:18:58',
                'deleted_at' => '2021-07-01 20:06:06',
            ),
            6 => 
            array (
                'id' => 7,
                'page_id' => 1,
                'sub_page_id' => NULL,
                'image' => '1629226967.png',
                'title' => 'Receba as nossas atualizações jurídicas',
                'title_en' => 'Receba as nossas atualizações jurídicas',
                'text' => '<p>Para ler onde e quando quiser. Selecione os temas de interesse e cadastre-se informando apenas seu nome completo e email para ficar por dentro das notícias jurídicas.</p>',
                'text_en' => '<p></p>',
                'link' => NULL,
                'text_link' => 'Cadastre seus dados',
                'text_link_en' => 'Cadastre seus dados',
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-08-17 19:19:11',
                'deleted_at' => '2021-07-01 20:06:06',
            ),
            7 => 
            array (
                'id' => 8,
                'page_id' => 2,
                'sub_page_id' => NULL,
                'image' => '1629231630.png',
                'title' => 'Alumni',
                'title_en' => 'Alumni',
                'text' => '<p>Fazer parte do nosso time, enfrentando desafios e alcançando resultados juntos, propicia a construção de relacionamentos de valor. Com o nosso Alumni, queremos manter contato com aqueles que foram nossos integrantes.</p>',
                'text_en' => '<p></p>',
                'link' => NULL,
                'text_link' => 'Conheça nosso Alumni',
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => '2021-07-28 13:47:11',
                'updated_at' => '2021-08-17 19:19:57',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'page_id' => 4,
                'sub_page_id' => NULL,
                'image' => '1629239141.png',
                'title' => 'Sobre nós',
                'title_en' => 'Sobre nós',
                'text' => '<p>Trabalhamos com <strong>questões complexas</strong> porque o desafio nos estimula. Trabalhamos com extrema dedicação e cuidado porque somos apaixonados pelo que fazemos. </p><p>Somos um escritório de advocacia com <strong>visão global</strong> e advogados <strong>especialistas</strong> em todas as áreas do Direito. Independente há mais de 75 anos, temos a ética e a <strong>excelência</strong> como valores fundamentais. Somos multidisciplinares e atuamos de forma ativa, plural e inovadora para potencializar o negócio de nossos clientes e aperfeiçoar a sociedade como um todo.</p>',
                'text_en' => '<p></p>',
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-08-17 20:21:19',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'page_id' => 4,
                'sub_page_id' => NULL,
                'image' => '1631559164.png',
                'title' => 'Pinheiro Neto Advogados',
                'title_en' => 'Pinheiro Neto Advogados',
                'text' => '<p>Multidisciplinares, especializados e em permanente evolução, trabalhamos para oferecer soluções jurídicas eficazes e contemporâneas que possibilitem a nossos clientes crescer e prosperar em ambientes cada vez mais complexos e desafiadores. </p><p>Comprometidos com os mais altos padrões éticos, primamos pela agilidade na busca de um atendimento eficaz e de alta qualidade. Independentes há 79 anos, adotamos a confiança, o profissionalismo e a transparência como valores fundamentais. Contamos com uma estrutura robusta de governança e atuamos com visão institucional.</p><p>Dispomos de equipes altamente qualificadas em todas as áreas do Direito, que mantêm vivos os valores e a tradição que nos trouxeram até aqui. Nossos integrantes são nosso maior atributo.</p><p>Com correspondentes em todo o Brasil e relacionamento estreito com vários escritórios de advocacia de primeira linha em diferentes países, estamos preparados para lidar com questões transnacionais de empresas de todos os portes, geografias e segmentos.</p><p>Sempre buscamos estar atentos e prontos para reagir às novas oportunidades, tendências e desafios, com trabalho sério, conhecimento profundo e respeito aos padrões de responsabilidade exigidos pela sociedade. </p><p>Sendo um escritório brasileiro de visão global, nosso desafio é compreender o futuro e buscar soluções que atendam às necessidades e anseios de nossos clientes. </p><p>Acreditamos que o Direito aprimora os negócios e a sociedade. Como tal, buscamos exercê-lo com excelência e respeito ao próximo.</p>',
                'text_en' => '<p></p>',
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-13 15:52:44',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'page_id' => 4,
                'sub_page_id' => NULL,
                'image' => NULL,
                'title' => 'Tradição em inovação',
                'title_en' => 'Tradição em inovação',
                'text' => '<p>Pioneirismo, tradição, inovação e excelência são marcas que cultivamos desde a nossa fundação, por J.M. Pinheiro Neto, em 1942. Visionário, foi ele quem, ao criar o escritório, trouxe o formato advogado-firma para o Brasil – até então, uma profissão individual.</p><p>Com quase oito décadas de atuação e clientes atendidos em mais de 80 países, desenvolvemos uma cultura própria e integrada, focada em evoluir a forma como os serviços jurídicos são prestados no Brasil.</p><p>Combinando tradição e inovação, praticamos uma abordagem dinâmica e exclusiva. Da tradição, trazemos a experiência e a excelência que nos prepararam para lidar com a complexidade do cenário jurídico brasileiro. </p><p>Mantemos, ao mesmo tempo, o olhar para o futuro: antecipamos possibilidades, criamos soluções inovadoras, investimos no desenvolvimento de talentos, somos ativos em ações de responsabilidade socioambiental, incentivando um ambiente plural e estando à frente de discussões relevantes para o País. </p><p>Foi assim em 2018, quando abrimos o escritório de Palo Alto, e nos consolidamos como a firma brasileira com maior representatividade no Vale do Silício, na Califórnia; e, em 2020, quando inauguramos o escritório de Tóquio, no Japão, que funciona como nosso hub na Ásia.</p><p>Neste início de década, marcado por transformações profundas e desafios jurídicos complexos, seguimos determinados a abraçar a mudança, esteja ela onde estiver e seja ela qual for. Afinal, tempos de imprevisibilidade demandam conhecimento, agilidade e adaptação.</p>',
                'text_en' => '<p></p>',
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-08-17 19:48:33',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'page_id' => 4,
                'sub_page_id' => NULL,
                'image' => NULL,
                'title' => 'Réplica da sala do Sr. Pinheiro na sede do nosso escritório em São Paulo',
                'title_en' => 'Réplica da sala do Sr. Pinheiro na sede do nosso escritório em São Paulo',
                'text' => '<p></p>',
                'text_en' => '<p></p>',
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-08-17 19:38:18',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'page_id' => 4,
                'sub_page_id' => NULL,
                'image' => '1631559797.png',
                'title' => 'Escola de Formação',
                'title_en' => 'Escola de Formação',
                'text' => '<p>Aprimoramos e complementamos os conhecimentos dos advogados desde o início da carreira, dando suporte para nossos integrantes desenvolverem seus talentos.</p>',
                'text_en' => '<p></p>',
                'link' => NULL,
                'text_link' => 'Conhecer Escola de Formação',
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-13 16:03:17',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'page_id' => 4,
                'sub_page_id' => NULL,
                'image' => '1631560104.png',
                'title' => 'Responsabilidade Social',
                'title_en' => 'Responsabilidade Social',
                'text' => '<p>Sonhamos com um mundo em que as pessoas tenham <strong>mais oportunidades.</strong> <br>Essa vontade nos motiva a olhar para a sociedade e a pensar como podemos devolver parte de tudo o que recebemos.</p>',
                'text_en' => '<p></p>',
                'link' => NULL,
                'text_link' => 'Ver projetos sociais',
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-13 16:08:24',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'page_id' => 4,
                'sub_page_id' => NULL,
                'image' => '1631560135.png',
                'title' => 'Diversidade e inclusão',
                'title_en' => 'Diversidade e inclusão',
                'text' => '<p>Acreditamos que valorizar a <strong>diversidade</strong> e garantir a <strong>inclusão</strong> é o certo a se fazer, incentivando discussões que criem um ambiente de trabalho acolhedor.</p>',
                'text_en' => '<p></p>',
                'link' => NULL,
                'text_link' => 'Acessar página',
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-13 16:08:55',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'page_id' => 4,
                'sub_page_id' => NULL,
                'image' => NULL,
                'title' => 'Reconhecimentos do Escritório',
                'title_en' => 'Reconhecimentos do Escritório',
                'text' => '<p>Conheça nossos principais destaques na publicações nacionais e internacionais mais relevantes.</p>',
                'text_en' => '<p></p>',
                'link' => NULL,
                'text_link' => 'Ver',
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-08-17 19:49:11',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'page_id' => 4,
                'sub_page_id' => NULL,
                'image' => '1631560200.png',
                'title' => 'Contato',
                'title_en' => 'Contato',
                'text' => '<p>Tem alguma dúvida, solicitação ou quer falar com a gente?</p>',
                'text_en' => '<p></p>',
                'link' => NULL,
                'text_link' => 'Entre em contato',
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-13 16:10:00',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'page_id' => 4,
                'sub_page_id' => NULL,
                'image' => '1631560222.png',
                'title' => 'Notícias do escritório',
                'title_en' => 'Notícias do escritório',
                'text' => '<p></p>',
                'text_en' => '<p></p>',
                'link' => NULL,
                'text_link' => 'Confira todas as notícias',
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-13 16:10:22',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'page_id' => NULL,
                'sub_page_id' => 1,
                'image' => '1631652629.png',
                'title' => 'Escola de Formação',
                'title_en' => 'Escola de Formação',
                'text' => '<p>Criada em 2012, nossa Escola de Formação é a primeira iniciativa desse porte no setor jurídico do Brasil e visa complementar a formação proporcionada pelo ensino acadêmico e agregar os conhecimentos necessários para que nossos advogados possam navegar por um universo jurídico cada vez mais complexo.</p><p>Com o propósito de desenvolver talentos e capacitá-los a prestar assessoria legal de vanguarda, dedicamo-nos a aprimorar e compartilhar conhecimentos por meio de um programa multidisciplinar, integrado por ciclos de treinamento personalizados.</p><p>O resultado dessa dedicação é a formação de um corpo jurídico com capacidades individuais e coletivas atualizadas e advogados cada vez mais preparados para assessorar nossos clientes de forma integrada, criativa e eficiente.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 17:50:29',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'page_id' => NULL,
                'sub_page_id' => 4,
                'image' => '1631654185.png',
                'title' => 'APOIAR. INCENTIVAR. CONECTAR.',
                'title_en' => 'APOIAR. INCENTIVAR. CONECTAR.',
                'text' => '<p><strong>Para transformar a sua história.<br>A nossa história.</strong></p><p>O olhar e as ações para a equidade compõem a nossa cultura e foram institucionalizados na Comissão da Mulher, criada há mais de 10 anos. A década de 2020, que nem bem começou, já apresenta desafios à altura das conquistas da nossa comissão, entre eles: ampliar a representatividade feminina nos cargos de gestão e liderança no escritório; aprimorar, ainda mais, o ambiente interno para nossas integrantes; e garantir a multiplicidade de visões.</p><p>Nós acreditamos que, ao <strong>apoiar</strong> genuinamente as nossas integrantes em suas carreiras, ao <strong>incentivá-las</strong> em seu desenvolvimento profissional e ao conectá-las entre si e com a <strong>liderança feminina</strong>, cumprimos com o nosso propósito: transformar as suas histórias e, com isso, a história de Pinheiro Neto Advogados.</p><p>Sabemos que é sempre possível evoluir e a nossa comissão, nascida em 2009 e pioneira no universo jurídico, vem confirmando isso, por meio de ações inovadoras e inspiradoras – ações essas reconhecidas e de sucessivas quebras de paradigmas. De forma genuína, debatemos, engajamos e promovemos a igualdade, impulsionando uma construção permanente da autoestima das nossas profissionais.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 18:16:25',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'page_id' => NULL,
                'sub_page_id' => 4,
                'image' => '1631654338.png',
                'title' => 'APOIAR. INCENTIVAR. CONECTAR.',
                'title_en' => 'APOIAR. INCENTIVAR. CONECTAR.',
                'text' => '<p>Mulheres conscientes inspiram e ampliam a visão de outras mulheres sobre sua situação na prática jurídica e no mercado corporativo. É por esta razão que estimulamos as nossas integrantes ao debate de temas contemporâneos e necessários na questão feminina.</p><p>Com nossas ações, procuramos responder a uma pergunta feita pelas mulheres em diferentes fases de suas vidas: É possível estar em um ambiente que garanta o entusiasmo profissional, conciliando a qualidade de vida pessoal a uma vida profissional saudável e bem-sucedida? </p><p> Nós, de Pinheiro Neto Advogados, estamos convencidos de que sim. Desde que estejamos juntos.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 18:18:58',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'page_id' => NULL,
                'sub_page_id' => 4,
                'image' => '1631655058.png',
                'title' => 'Visão plural',
                'title_en' => 'Visão plural',
                'text' => '<p>Nossa comissão é composta por sócias, sócios, associadas, associados e integrantes do administrativo. Com o passar dos anos, fomos entendendo o papel essencial dos aliados em nosso grupo e foi graças a essa visão co-construída que a comissão se tornou tão representativa dentro do escritório e no universo jurídico brasileiro, sendo hoje referência para profissionais de múltiplas gerações.</p>',
                'text_en' => '<p>Nossa comissão é composta por sócias, sócios, associadas, associados e integrantes do administrativo. Com o passar dos anos, fomos entendendo o papel essencial dos aliados em nosso grupo e foi graças a essa visão co-construída que a comissão se tornou tão representativa dentro do escritório e no universo jurídico brasileiro, sendo hoje referência para profissionais de múltiplas gerações.</p>',
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 18:32:05',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'page_id' => NULL,
                'sub_page_id' => 4,
                'image' => '1631671609.png',
                'title' => 'Eventos',
                'title_en' => 'Eventos',
                'text' => '<p>Palestras e debates sobre carreira e vida pessoal, com geração de networking e discussão de temas relevantes, como equidade de gênero e o papel da mulher na prática jurídica, entre outros, compõem nossos eventos. Destinados aos públicos interno e, por vezes, também externo, eles oferecem aos convidados a oportunidade de aprender com líderes femininas em suas respectivas áreas de atuação que, generosamente, compartilham as suas jornadas pessoais e profissionais, acrescendo debates sobre assuntos de interesse público.</p>',
                'text_en' => '<p>Palestras e debates sobre carreira e vida pessoal, com geração de networking e discussão de temas relevantes, como equidade de gênero e o papel da mulher na prática jurídica, entre outros, compõem nossos eventos. Destinados aos públicos interno e, por vezes, também externo, eles oferecem aos convidados a oportunidade de aprender com líderes femininas em suas respectivas áreas de atuação que, generosamente, compartilham as suas jornadas pessoais e profissionais, acrescendo debates sobre assuntos de interesse público.</p>',
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 23:06:49',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'page_id' => NULL,
                'sub_page_id' => 4,
                'image' => '1631671622.png',
                'title' => 'Datas especiais',
                'title_en' => 'Datas especiais',
                'text' => '<p>O Dia Internacional da Mulher, festejado em 8 de março, assim como outras datas importantes, é lembrado em eventos especiais no escritório, procurando conscientizar os nossos integrantes sobre a importância da equidade de gênero na sociedade e no Direito. Já o Outubro Rosa, conhecido mundialmente pelo laço rosa que simboliza a luta da mulher contra o câncer de mama, é objeto de uma campanha realizada há anos pelo escritório em busca de conscientização e bem-estar. Em outubro, também executamos dinâmicas, workshops e palestras voltados à saúde da mulher no cuidado e prevenção, eventos como o Mulheres no Esporte e campanhas internas para doação de lenços, de cortes de cabelo e itens utilizados para aliviar os efeitos da quimioterapia e da radioterapia. Assim como alguns dos principais monumentos paulistanos e globais, nosso prédio recebe iluminação rosa, aderindo publicamente à campanha.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 23:07:02',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'page_id' => NULL,
                'sub_page_id' => 4,
                'image' => '1631671629.png',
                'title' => 'Bate-papos internos',
                'title_en' => 'Bate-papos internos',
                'text' => '<p>Nestes encontros, as nossas advogadas, especialmente as mais jovens, trocam experiências com sócias e consultoras, desenvolvendo um maior senso de proximidade e pertencimento. Ao compartilhar situações vivenciadas, impressões e sentimentos, nossas integrantes têm uma interação próxima e genuína. Dessas conversas, que por si só geram ideias e soluções criativas para as situações do dia a dia, também resultam diversas ações, como, por exemplo, o projeto de Mentoria, implementado a partir de uma escuta ativa das sócias e consultoras sobre as necessidades das advogadas integrantes do escritório.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 23:07:09',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'page_id' => NULL,
                'sub_page_id' => 4,
                'image' => '1631671640.png',
                'title' => 'Happy hour com mulheres inspiradoras',
                'title_en' => 'Happy hour com mulheres inspiradoras',
                'text' => '<p>Já nestes encontros, a interação é com convidadas externas engajadas na atuação em prol da equidade de gênero: são profissionais que trazem resultados de pesquisas realizadas, experiências e as melhores práticas de suas instituições, suas próprias trajetórias e, com isso, inspiram-nos enquanto coletividade para buscarmos sempre o contínuo aprimoramento como instituição e indivíduos. Aqui, olhamos para o mercado e ao que podemos trazer de melhor para o escritório e nossas mulheres, bem como entendemos com quais projetos podemos colaborar.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 23:07:20',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'page_id' => NULL,
                'sub_page_id' => 4,
                'image' => '1631671648.png',
                'title' => 'CM Recomenda',
                'title_en' => 'CM Recomenda',
                'text' => '<p>CM Recomenda é um <strong>clipping mensal</strong> destinado a todos os nossos integrantes com o objetivo de divulgar de artigos, pesquisas, bate-papos, palestras e ações promovidas por clientes, grupos de afinidades e/ou terceiros que fomentam o debate de diversos assuntos como: parentalidade, saúde mental, desenvolvimento da carreira das mulheres, reconhecimento de suas habilidades e competências. Com isso, promovemos o intercâmbio das melhores práticas de equidade de gênero na sociedade e no Direito.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 23:07:28',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'page_id' => NULL,
                'sub_page_id' => 4,
                'image' => '1631671657.png',
                'title' => 'Projeto de mentoria',
                'title_en' => 'Projeto de mentoria',
            'text' => '<p>O projeto de mentoria é importante e pioneiro para o escritório. Com sua primeira edição em 2021, ele tem como objetivo formar mentores(as) e mentoradas em prol da multiplicação da cultura, dos princípios e valores do escritório,  bem como do fomento de uma liderança feminina inclusiva e do desenvolvimento de toda potencialidade da carreira profissional das associadas. Nele as associadas potencializarão o seu crescimento profissional, serão preparadas para situações desafiadoras na carreira e despertarão seus potenciais ao conhecerem as experiências dos mentores. Já os mentores, homens e mulheres da liderança, auxiliarão a reforçar e transmitir a cultura e os valores do escritório, ajudarão a formar uma liderança feminina inclusiva e contribuirão com o desenvolvimento das associadas.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 23:07:37',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'page_id' => NULL,
                'sub_page_id' => 4,
                'image' => '1631671664.png',
                'title' => 'Treinamentos e grupos de trabalho',
                'title_en' => 'Treinamentos e grupos de trabalho',
                'text' => '<p>Ao longo do ano, qualificamos as profissionais interessadas em realizar treinamentos voltados à questão de gênero e outros temas, por meio de palestras e minicursos oferecidos por empresas especializadas. Grupos de trabalho tratam, por sua vez, de políticas e melhores práticas para aproximação e aprendizagem sobre assuntos diversos.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 23:07:44',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'page_id' => NULL,
                'sub_page_id' => 4,
                'image' => '1631671674.png',
                'title' => 'Trabalho em período parcial',
                'title_en' => 'Trabalho em período parcial',
                'text' => '<p>Solução moderna encontrada para balancear vida pessoal e profissional, passamos a oferecer o programa part-time a nossas associadas seniores, o que lhes permite dedicar tempo e energia a suas prioridades, sem prejuízo às demandas do escritório.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 23:07:54',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'page_id' => NULL,
                'sub_page_id' => 4,
                'image' => '1631671682.png',
                'title' => 'Licença-maternidade  estendida',
                'title_en' => 'Licença-maternidade  estendida',
            'text' => '<p>Fomos o primeiro escritório de advocacia do País a aderir ao programa “Empresa Cidadã” (Lei 11.770), em 2016, garantindo às nossas integrantes a licença-maternidade de seis meses. Entre os benefícios dessa ampliação, estão a facilitação da amamentação exclusiva nos seis primeiros meses de vida do bebê, o fortalecimento do sistema imunológico da criança e o reforço do vínculo entre mãe e filho.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 23:08:02',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'page_id' => NULL,
                'sub_page_id' => 4,
                'image' => '1631671692.png',
                'title' => 'Licença-paternidade de 20  dias ',
                'title_en' => 'Licença-paternidade de 20  dias ',
                'text' => '<p>Com a licença-paternidade de 20 dias, incentivamos o equilíbrio de responsabilidades – por entender que os pais devem participar dos primeiros dias da chegada de seus filhos, dividindo com as mães as tarefas e instituindo, assim, um ambiente favorável a todos.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 23:08:12',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'page_id' => NULL,
                'sub_page_id' => 4,
                'image' => '1631671703.png',
                'title' => 'Programa Welcome Back ',
                'title_en' => 'Programa Welcome Back ',
                'text' => '<p>Retornar ao trabalho sempre gera expectativa para a mãe, que passou meses voltada às necessidades do bebê. Para tornar esse retorno o mais natural possível e promover uma real sensação de acolhimento, oferecemos a ela apoio na reintegração ao trabalho. Este atendimento é realizado de maneira voluntária pelas integrantes do escritório e a adesão ao programa é optativa.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 23:08:23',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'page_id' => NULL,
                'sub_page_id' => 4,
                'image' => '1631671712.png',
                'title' => 'Espaço Mãe ',
                'title_en' => 'Espaço Mãe ',
                'text' => '<p>As integrantes do escritório, desde o seu período gestacional até 3 anos do bebê, têm à sua disposição um espaço privativo e confortável dentro do escritório, silencioso e com infraestrutura planejada. O mesmo ambiente serve para aleitamento e armazenamento do leite na fase de amamentação, assim como para troca de experiência entre as mães e descanso neste momento tão especial. A sala também pode ser utilizada por visitantes e clientes do escritório. Como conforto adicional às integrantes, ainda disponibilizamos itens de uso pessoal nos banheiros femininos.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 23:08:32',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'page_id' => NULL,
                'sub_page_id' => 4,
                'image' => '1631671720.png',
                'title' => 'Estacionamento para gestantes',
                'title_en' => 'Estacionamento para gestantes',
                'text' => '<p>Reservamos vagas exclusivas para gestantes em nossos endereços, localizados em São Paulo. Futuras mães contam com a comodidade de estacionar dentro dos prédios e perto dos principais acessos, sendo poupadas de percorrer longas distâncias.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 23:08:40',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'page_id' => NULL,
                'sub_page_id' => 4,
                'image' => '1631671728.png',
                'title' => 'Participação nos lucros ',
                'title_en' => 'Participação nos lucros ',
            'text' => '<p>Durante a licença-maternidade e a sua extensão, nossas integrantes se mantêm no Plano de Participação nos Lucros e Resultados (PPLR) do escritório. Nesse período, elas recebem participação nos lucros com base na média de recebimento dos seis últimos meses anteriores à licença ou no recebimento do mês, prevalecendo o maior valor.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 23:08:48',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'page_id' => NULL,
                'sub_page_id' => 4,
                'image' => '1631671735.png',
                'title' => 'Auxílio-creche',
                'title_en' => 'Auxílio-creche',
            'text' => '<p>Benefício garantido na Consolidação das Leis do Trabalho (CLT) e regulado por Convenções Coletivas, o auxílio-creche é destinado a todas as mães, que possuem direito a receber o auxílio financeiro por, no mínimo, seis meses após o nascimento do bebê. Mediante comprovação nominal dos gastos com creche ou instituição análoga, o auxílio é estendido para cada filho de até cinco anos, 11 meses e 29 dias.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 23:08:55',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'page_id' => NULL,
                'sub_page_id' => 2,
                'image' => '1631656968.png',
                'title' => 'Construção da cidadania',
                'title_en' => 'Construção da cidadania',
            'text' => '<p>A responsabilidade social nasceu junto com a nossa história, herança e legado deixados pelo nosso fundador José Martins Pinheiro Neto. Surgimos como escritório e como apoiadores de iniciativas de responsabilidade social (à época chamadas de atividades filantrópicas) com a vontade de acolher e incentivar o desenvolvimento de pessoas. </p><p>Sonhamos, há muitos anos, com um mundo em que todos tenham mais oportunidades. E esta vontade nos motiva não só a investir no aprimoramento e no futuro de nossos integrantes, mas também a olhar para a sociedade e pensar como podemos retribuir parte de tudo aquilo que recebemos.</p><p>Acreditamos que ajudar a transformar outras histórias e agir em prol da coletividade é nosso dever e nos impacta profundamente. E fazemos isso sempre apoiando entidades com recursos financeiros (doações do caixa e alocações de verbas incentivadas), como voluntários em projetos e com trabalhos em casos pro bono.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => 'Faça o download do relatório social',
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 19:02:48',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'page_id' => NULL,
                'sub_page_id' => 2,
                'image' => '1631657027.png',
                'title' => 'Pro Bono',
                'title_en' => 'Pro Bono',
            'text' => '<p>Pro bono é uma expressão latina que significa “para o bem”. Na advocacia, diz respeito à prestação de serviços jurídicos sem custo algum. Presente desde a nossa fundação, a prestação de serviço pro bono é desempenhada por integrantes especialistas no tema compatível com cada caso e nunca como forma de treinamento.</p><p>Somos o primeiro escritório de advocacia do Brasil a remunerar igualmente integrantes em casos pagos ou gratuitos, de forma que nosso programa pro bono é totalmente institucionalizado. Com isso, levamos o nosso trabalho pro bono a outro patamar de qualidade e exigência — o mesmo que usamos com nossos clientes pagantes.</p><p>Além da procura de nossos parceiros sociais, recebemos casos de clearing houses, como o Instituto Pro Bono e o TrustLaw (Thomson Reuters), que nos conectam a projetos em todas as regiões do Brasil e do mundo.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 19:03:47',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'page_id' => NULL,
                'sub_page_id' => 2,
                'image' => '1631657178.png',
                'title' => 'Investimento  Socioambiental',
                'title_en' => 'Investimento  Socioambiental',
                'text' => '<p>Seja diretamente ou por meio das leis de incentivo, promovemos o repasse de recursos privados para projetos sociais, ambientais e culturais de interesse público. </p><p>A totalidade das verbas incentivadas são direcionadas exclusivamente aos projetos de responsabilidade social, não havendo nenhum direcionamento para projetos de comunicação, promoção e marketing.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => 'Faça o download do material completo',
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 19:06:18',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'page_id' => NULL,
                'sub_page_id' => 2,
                'image' => '1631657231.png',
                'title' => 'Voluntariado',
                'title_en' => 'Voluntariado',
                'text' => '<p>O time de voluntariado de Pinheiro Neto Advogados está sempre alerta – um exército de solidários que, sempre que chamado, se apresenta cheio de disposição para as mais diversas tarefas: mutirões de cidadania com plantões jurídicos, palestras, campanhas de doação de sangue, mentorias e aulas de inglês para jovens e reformas de espaços de convivência para crianças e adolescentes.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 19:07:11',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'page_id' => NULL,
                'sub_page_id' => 2,
                'image' => NULL,
                'title' => 'Conheça nossos parceiros',
                'title_en' => 'Conheça nossos parceiros',
                'text' => NULL,
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 21:51:42',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'page_id' => NULL,
                'sub_page_id' => 3,
                'image' => '1631668012.png',
                'title' => 'Cultura de Diversidade',
                'title_en' => 'Cultura de Diversidade',
                'text' => '<p>Acreditamos que incentivar a <strong>diversidade</strong> é o certo a se fazer não só para termos um <strong>ambiente acolhedor</strong> a nossos integrantes, mas porque não investir em diversidade significa perder talentos. Ao atuar para aprimorar nosso ambiente interno, pretendemos criar as oportunidades para que todos se sintam seguros para serem quem são e mais motivados a construir suas carreiras em um escritório que os valoriza como pessoa. Por acreditarmos em uma cultura de respeito à pluralidade e inclusão, institucionalizamos nosso compromisso ao criar a <strong>Comissão de Diversidade e Inclusão e a Comissão da Mulher</strong>.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 22:14:19',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'page_id' => NULL,
                'sub_page_id' => 3,
                'image' => '1631668165.png',
                'title' => 'Comissão de Diversidade  e Inclusão',
                'title_en' => 'Comissão de Diversidade  e Inclusão',
                'text' => '<p>Para nós, valorizar a diversidade e garantir a inclusão é o certo a se fazer. Trabalhamos para incentivar a discussão de assuntos que visam valorizar pessoas e enriquecer comportamentos e culturas, o que resulta em opiniões mais ricas e profundas.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => 'Conheça a comissão',
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 22:14:29',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'page_id' => NULL,
                'sub_page_id' => 3,
                'image' => '1631668570.png',
                'title' => 'Comissão da Mulher',
                'title_en' => 'Comissão da Mulher',
                'text' => '<p>Ao apoiar genuinamente as nossas integrantes em suas carreiras, ao incentivá-las em seu desenvolvimento profissional e ao conectá-las entre si e com a liderança feminina, cumprimos com o nosso propósito: transformar as suas histórias e, com isso, a história de Pinheiro Neto Advogados.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => 'Conheça a Comissão da Mulher',
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 22:16:10',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'page_id' => NULL,
                'sub_page_id' => 3,
                'image' => '1631668611.png',
                'title' => 'Responsabilidade Social',
                'title_en' => 'Responsabilidade Social',
                'text' => '<p>Sonhamos com um mundo em que as <strong>pessoas</strong> tenham mais <strong>oportunidades</strong>. Essa vontade nos motiva a olhar para a <strong>sociedade</strong> e a pensar como podemos devolver parte de tudo o que recebemos.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => 'Ver projetos sociais',
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 22:09:25',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'page_id' => NULL,
                'sub_page_id' => 5,
                'image' => '1631669219.png',
                'title' => 'Incluir para ser plural. Incluir para fazer o certo.',
                'title_en' => 'Incluir para ser plural. Incluir para fazer o certo.',
                'text' => '<p>Se, para ser incluído, for necessário esconder alguma característica essencial, não há inclusão verdadeira. </p><p>Encorajar o respeito pelas diferenças, estabelecer boas práticas e desenvolver um ambiente plural em que cor, raça, gênero, etnia, características físicas e pessoais, origem, idade, credo religioso, orientação sexual e convicção política não nos impeçam de ser quem somos.</p><p>Desde 2010, a <strong>Comissão de Diversidade e Inclusão</strong> tem como objetivo incentivar uma atmosfera acolhedora nos campos de:</p><ul><li><p>LGBTQIA+</p></li><li><p>Equidade de gênero</p></li><li><p>Pessoas com deficiência</p></li><li><p>Equidade racial</p></li><li><p>Diversidade geográfica</p></li><li><p>Liberdade religiosa</p></li></ul><p>Para nós, valorizar a <strong>diversidade</strong> e garantir a <strong>inclusão</strong> é o certo a se fazer. Incluir é ação, é disposição para o encontro, é mudança, é gesto concreto para a inclusão de pessoas e das perspectivas que elas trazem consigo.</p><p>Trabalhamos para incentivar a discussão de assuntos que visam valorizar pessoas e enriquecer comportamentos e culturas, o que resulta em opiniões mais ricas e profundas. Questões complexas exigem <strong>responsabilidade, pluralidade de opinião, multidisciplinaridade, relações humanizadas e inovação</strong> constante para uma melhor tomada de decisão. </p><p>Como líderes na área jurídica, não nos abstemos do debate. Pelo contrário, nós atuamos para influenciá-lo positivamente.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => '',
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 22:26:59',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'page_id' => NULL,
                'sub_page_id' => 5,
                'image' => '1631669372.png',
                'title' => 'Visão plural',
                'title_en' => 'Visão plural',
                'text' => '<p>Tendo como um de seus desafios criar um ambiente receptivo às diferenças, a <strong>Comissão de Diversidade e Inclusão</strong> tem um modelo de diretoria fracionada, composta por 6 sócios de praticamente todas as áreas do escritório. Já o Comitê de Diversidade e Inclusão, por sua vez, reúne integrantes do jurídico e administrativo.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 22:29:32',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'page_id' => NULL,
                'sub_page_id' => 5,
                'image' => '1631670716.png',
                'title' => 'LGBTQIA+',
                'title_en' => 'LGBTQIA+',
                'text' => '<p>Para garantir o <strong>cuidado</strong> e a <strong>liberdade</strong> de manifestação de integrantes LGBTQIA+ do escritório, abordamos e debatemos macrotendências e questões como <strong>orientação sexual</strong> e <strong>diversidade de gênero</strong>, assim como boas práticas corporativas, em ações diversas dedicadas ao tema. Dentre outras ações, anualmente estendemos a bandeira LGBTQIA+ na fachada da sede, em São Paulo, para celebrar o Dia Internacional do Orgulho LGBTQIA+.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 22:51:56',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'page_id' => NULL,
                'sub_page_id' => 5,
                'image' => '1631670725.png',
                'title' => 'Equidade de Gênero',
                'title_en' => 'Equidade de Gênero',
                'text' => '<p>Com a <strong>Comissão da Mulher</strong>, nós acreditamos que, ao apoiar genuinamente as nossas integrantes em suas carreiras, ao <strong>incentivá-las</strong> em seu desenvolvimento profissional e ao <strong>conectá-las</strong> entre si e com colegas, cumprimos o nosso propósito: <strong>transformar</strong> as suas <strong>histórias</strong> e, com isso, a história de Pinheiro Neto Advogados.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 22:52:05',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'page_id' => NULL,
                'sub_page_id' => 5,
                'image' => '1631670733.png',
                'title' => 'Pessoas com deficiência',
                'title_en' => 'Pessoas com deficiência',
            'text' => '<p>Pioneiros entre os escritórios do País em adotar a legislação trabalhista referente às pessoas com deficiência física e intelectual, atuamos com os instrumentos necessários para que profissionais com individualidades distintas tenham <strong>autonomia</strong> para realizar o seu trabalho, inibindo os vieses inconscientes e o capacitismo (discriminação e o preconceito social contra pessoas com alguma deficiência) no ambiente de trabalho.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 22:52:13',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'page_id' => NULL,
                'sub_page_id' => 5,
                'image' => '1631670764.png',
                'title' => 'Equidade racial',
                'title_en' => 'Equidade racial',
            'text' => '<p>Somos cofundadores da Aliança Jurídica pela Equidade Racial, lançada em 2018, em parceria com os principais escritórios de advocacia do País. Iniciativa <strong>pioneira</strong>, a Aliança visa promover maior <strong>inclusão</strong> de profissionais negros no mercado jurídico e também o debate da representatividade negra no Direito brasileiro. Além disso, participamos do Projeto Incluir Direito, que estimula jovens negros a participar em condição de <strong>igualdade</strong> nos processos seletivos das sociedades de advogados associadas ao Centro de Estudos das Sociedades de Advogados (Cesa).</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 22:53:08',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'page_id' => NULL,
                'sub_page_id' => 5,
                'image' => '1631670828.png',
                'title' => 'Diversidade geográfica',
                'title_en' => 'Diversidade geográfica',
            'text' => '<p>Desde 2018, mantemos convênios de estágio com as Faculdades de Direito da Universidade Federal de Pernambuco (UFPE), da Universidade Federal da Bahia (UFBA) e da Universidade Federal do Ceará (UFC), convidando estudantes a participar do <strong>estágio de férias</strong> em nossos escritórios.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 22:53:51',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'page_id' => NULL,
                'sub_page_id' => 5,
                'image' => '1631670897.png',
                'title' => 'Apoio ao Ismart',
                'title_en' => 'Apoio ao Ismart',
            'text' => '<p>Oferecemos apoio ao Instituto Social para Motivar, Apoiar e Reconhecer Talentos (Ismart) – entidade privada, sem fins lucrativos, que identifica jovens talentos de baixa renda. O objetivo é conceder a eles <strong>bolsas</strong> em <strong>escolas particulares</strong> de excelência, bem como acesso a programas de desenvolvimento e orientação profissional, do ensino fundamental à universidade. Estudantes de Direito vinculados ao Ismart ingressam no escritório como estagiários e têm, ao longo de sua jornada, sócios como seus mentores individuais.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 22:54:57',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'page_id' => NULL,
                'sub_page_id' => 5,
                'image' => '1631670934.png',
                'title' => 'Contratação e retenção de talentos',
                'title_en' => 'Contratação e retenção de talentos',
                'text' => '<p>Ao <strong>atuar estrategicamente</strong> junto às áreas de recrutamento e seleção de pessoas, treinamento e comunicação interna, acompanhamos casos que exijam observação apurada e acolhimento especial na temática da <strong>diversidade</strong> e <strong>inclusão</strong>. Mantemos, igualmente, uma ouvidoria para garantir que nossos integrantes tenham canal aberto com o escritório, compreendendo as distintas vertentes do tema.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 22:55:47',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'page_id' => NULL,
                'sub_page_id' => 5,
                'image' => '1631671001.png',
                'title' => 'Revista Bravo!',
                'title_en' => 'Revista Bravo!',
                'text' => '<p>Para debater a <strong>diversidade</strong> em suas mais diferentes frentes, criamos, em parceria com a Revista Bravo!, o “Além do Gênero”, iniciativa de <strong>conteúdo</strong> voltada à construção e ao fortalecimento de uma cultura de <strong>diversidade e inclusão</strong>. O material produzido pode ser acessado em http://bravo.vc/seasons/s06e04.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 22:57:41',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'page_id' => NULL,
                'sub_page_id' => 5,
                'image' => '1631671111.png',
                'title' => 'Treinamentos',
                'title_en' => 'Treinamentos',
                'text' => '<p>Por acreditar que a diversidade e inclusão é parte significativa dos <strong>valores</strong> do escritório, ao longo do ano, oferecemos <strong>treinamentos e cursos</strong> em instituições renomadas com as quais temos parcerias.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 22:58:31',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'page_id' => NULL,
                'sub_page_id' => 5,
                'image' => '1631671151.png',
                'title' => 'Selo de Direitos Humanos',
                'title_en' => 'Selo de Direitos Humanos',
                'text' => '<p>Somos o <strong>único escritório brasileiro</strong> a ter recebido o Selo de Direitos Humanos da Cidade de São Paulo em todas as suas 3 edições. Além disso, somos o único escritório brasileiro a ser reconhecido com o Selo Estadual de Diversidade do Governo do Estado de São Paulo em todas as suas 4 edições.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 22:59:23',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'page_id' => NULL,
                'sub_page_id' => 5,
                'image' => '1631671306.png',
                'title' => 'Nada Mais, Nada Menos',
                'title_en' => 'Nada Mais, Nada Menos',
                'text' => '<p>Desde 2018, somos signatários da Carta de Apoio à Diversidade, ao Respeito e à Inclusão de Pessoas LGBT+ nos Locais de Trabalho no Brasil, com o objetivo de reafirmar a crença e compromisso com a <strong>diversidade e inclusão nos locais de trabalho</strong> para todas as pessoas no Brasil, incluindo as pessoas LGBTQIA+.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 23:01:49',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'page_id' => NULL,
                'sub_page_id' => 5,
                'image' => '1631671346.png',
                'title' => 'ONU Livres & Iguais',
                'title_en' => 'ONU Livres & Iguais',
                'text' => '<p>Desde 2017, somos signatários da carta de campanha global do Escritório de Direitos Humanos das Nações Unidas contra a homofobia e a transfobia, que tem o objetivo de promover <strong>direitos iguais</strong> e tratamento justo para pessoas LGBTQIA+.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 23:02:28',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'page_id' => NULL,
                'sub_page_id' => 5,
                'image' => '1631671386.png',
                'title' => 'Bolsas de estudo',
                'title_en' => 'Bolsas de estudo',
                'text' => '<p>Com o objetivo de promover a igualdade entre os integrantes, o escritório, em parceria com a Cultura Inglesa, concede <strong>10 bolsas de estudos</strong> por ano em cursos regulares de inglês para estagiários e associados, que necessitam de apoio financeiro para aperfeiçoar o idioma.</p>',
                'text_en' => NULL,
                'link' => NULL,
                'text_link' => NULL,
                'text_link_en' => NULL,
                'embed' => NULL,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2021-09-14 23:03:09',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}