<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class EventsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('events')->delete();
        
        \DB::table('events')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'Evento online gratuito sem palestrante e hora',
                'title_en' => 'Evento online gratuito sem palestrante, hora',
                'slug' => 'evento-online-gratuito-sem-palestrante-e-hora',
                'free' => 1,
                'date' => '2022-01-07',
                'hour' => NULL,
                'online' => 1,
                'local' => NULL,
                'address' => NULL,
                'lat' => NULL,
                'long' => NULL,
                'vacancies' => 100,
                'amount' => NULL,
                'external' => NULL,
                'link' => NULL,
                'image' => '1632494852.png',
                'text' => '<p>txt</p>',
                'text_en' => NULL,
                'publish' => 1,
                'highlight' => 1,
                'created_at' => '2021-09-22 16:08:54',
                'updated_at' => '2021-09-24 11:47:32',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'Evento presencial com palestrantes e externo',
                'title_en' => 'Evento presencial com palestrantes e externo',
                'slug' => 'evento-presencial-com-palestrantes-e-externo',
                'free' => NULL,
                'date' => '2021-12-25',
                'hour' => '12:05:00',
                'online' => 0,
                'local' => 'teste',
                'address' => NULL,
                'lat' => NULL,
                'long' => NULL,
                'vacancies' => 50,
                'amount' => '100',
                'external' => 1,
                'link' => 'https://www.google.com.br/',
                'image' => '1632500300.png',
                'text' => '<p>nnnn</p>',
                'text_en' => NULL,
                'publish' => 1,
                'highlight' => NULL,
                'created_at' => '2021-09-24 13:18:20',
                'updated_at' => '2021-09-24 13:18:20',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'Evento presencial gratuito com palestrantes e interno',
                'title_en' => 'Evento presencial gratuito com palestrantes e interno',
                'slug' => 'evento-presencial-gratuito-com-palestrantes-e-interno',
                'free' => 1,
                'date' => '2021-12-09',
                'hour' => '16:00:00',
                'online' => 0,
                'local' => 'teste',
                'address' => NULL,
                'lat' => NULL,
                'long' => NULL,
                'vacancies' => 500,
                'amount' => NULL,
                'external' => NULL,
                'link' => NULL,
                'image' => '1632501314.png',
                'text' => '<p>ssssscadacca</p>',
                'text_en' => NULL,
                'publish' => 1,
                'highlight' => 1,
                'created_at' => '2021-09-24 13:35:14',
                'updated_at' => '2021-09-24 13:47:24',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'Evento presencial com palestrantes e interno',
                'title_en' => 'Evento presencial  com palestrantes e interno',
                'slug' => 'evento-presencial-com-palestrantes-e-interno',
                'free' => 0,
                'date' => '2021-12-09',
                'hour' => '16:00:00',
                'online' => 0,
                'local' => 'teste',
                'address' => NULL,
                'lat' => NULL,
                'long' => NULL,
                'vacancies' => 500,
                'amount' => '150',
                'external' => NULL,
                'link' => NULL,
                'image' => '1632501402.png',
                'text' => '<p>ssssscadacca</p>',
                'text_en' => NULL,
                'publish' => 1,
                'highlight' => NULL,
                'created_at' => '2021-09-24 13:36:42',
                'updated_at' => '2021-09-24 13:36:42',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'evento passado',
                'title_en' => 'evento passado',
                'slug' => 'evento-passado',
                'free' => 1,
                'date' => '2021-09-03',
                'hour' => NULL,
                'online' => 1,
                'local' => NULL,
                'address' => NULL,
                'lat' => NULL,
                'long' => NULL,
                'vacancies' => 20,
                'amount' => NULL,
                'external' => NULL,
                'link' => NULL,
                'image' => '1632502040.png',
                'text' => '<p>\\lcmçsc dskçsdvç</p>',
                'text_en' => NULL,
                'publish' => 1,
                'highlight' => NULL,
                'created_at' => '2021-09-24 13:47:20',
                'updated_at' => '2021-09-24 13:47:22',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 8,
                'title' => 'teste',
                'title_en' => 'teste',
                'slug' => 'teste',
                'free' => 1,
                'date' => '2021-11-13',
                'hour' => '10:00:00',
                'online' => 1,
                'local' => NULL,
                'address' => NULL,
                'lat' => NULL,
                'long' => NULL,
                'vacancies' => NULL,
                'amount' => NULL,
                'external' => NULL,
                'link' => NULL,
                'image' => '1632508130.png',
                'text' => '<p>cx xc,; ,cx; </p>',
                'text_en' => NULL,
                'publish' => 1,
                'highlight' => NULL,
                'created_at' => '2021-09-24 15:28:50',
                'updated_at' => '2021-09-24 15:28:50',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 9,
                'title' => 'teste2',
                'title_en' => 'teste',
                'slug' => 'teste2',
                'free' => 1,
                'date' => '2021-11-13',
                'hour' => '10:00:00',
                'online' => 1,
                'local' => NULL,
                'address' => NULL,
                'lat' => NULL,
                'long' => NULL,
                'vacancies' => NULL,
                'amount' => NULL,
                'external' => NULL,
                'link' => NULL,
                'image' => '1632508228.png',
                'text' => '<p>cx xc,; ,cx; </p>',
                'text_en' => NULL,
                'publish' => 1,
                'highlight' => NULL,
                'created_at' => '2021-09-24 15:30:28',
                'updated_at' => '2021-09-24 15:30:28',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}