<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TimelinesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('timelines')->delete();
        
        \DB::table('timelines')->insert(array (
            0 => 
            array (
                'id' => 1,
                'year' => 1939,
                'title' => 'Graduação em Direito pela USP',
                'title_en' => 'Graduação em Direito pela USP',
                'text' => '<p>José Martins Pinheiro Neto recebe o diploma de graduação da Faculdade de Direito da Universidade de São Paulo.</p>',
                'text_en' => NULL,
                'image' => '1631723132.png',
                'publish' => 1,
                'created_at' => '2021-09-15 13:25:32',
                'updated_at' => '2021-09-15 13:25:32',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'year' => 1940,
                'title' => 'Viagem à Inglaterra',
                'title_en' => 'Viagem à Inglaterra',
                'text' => '<p>J.M. Pinheiro Neto vai à Inglaterra, onde atua como correspondente da BBC e cronista do jornal O Estado de S. Paulo.</p>',
                'text_en' => NULL,
                'image' => '1631723276.png',
                'publish' => 1,
                'created_at' => '2021-09-15 13:27:56',
                'updated_at' => '2021-09-15 13:27:56',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'year' => 1942,
                'title' => '1° escritório no centro de  São Paulo',
                'title_en' => '1° escritório no centro de  São Paulo',
                'text' => '<p>J.M. Pinheiro Neto vai à Inglaterra, onde atua como correspondente da BBC e cronista do jornal O Estado de S. Paulo.</p>',
                'text_en' => NULL,
                'image' => '1631723323.png',
                'publish' => 1,
                'created_at' => '2021-09-15 13:28:43',
                'updated_at' => '2021-09-15 13:28:43',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'year' => 1961,
                'title' => 'Clientes internacionais',
                'title_en' => 'Clientes internacionais',
                'text' => '<p>Com quase 20 anos de existência, empresas estrangeiras formam uma parcela expressiva da carteira de clientes.</p>',
                'text_en' => NULL,
                'image' => '1631723423.png',
                'publish' => 1,
                'created_at' => '2021-09-15 13:30:23',
                'updated_at' => '2021-09-15 13:30:23',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'year' => 1964,
                'title' => 'Mudança de nome e de endereço',
                'title_en' => 'Mudança de nome e de endereço',
                'text' => '<p>J.M. Pinheiro Neto abre seu escritório na Rua José Bonifácio, centro de São Paulo, com uma secretária e um office boy.</p>',
                'text_en' => NULL,
                'image' => '1631723468.png',
                'publish' => 1,
                'created_at' => '2021-09-15 13:31:08',
                'updated_at' => '2021-09-15 13:31:11',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'year' => 1969,
                'title' => 'Expansão do escritório para  o Rio de Janeiro',
                'title_en' => 'Expansão do escritório para  o Rio de Janeiro',
                'text' => '<p>Em 1º de setembro, com 106 integrantes, o escritório se expande para o Rio de Janeiro, instalando-se na Av. Rio Branco.</p>',
                'text_en' => NULL,
                'image' => '1631723507.png',
                'publish' => 1,
                'created_at' => '2021-09-15 13:31:47',
                'updated_at' => '2021-09-15 13:34:02',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'year' => 1973,
                'title' => 'Negócios com o Japão',
                'title_en' => 'Negócios com o Japão',
                'text' => '<p>J. M. Pinheiro Neto visita o Japão a convite da Câmara de Comércio e Indústria Japonesa no Brasil. Desde então, o relacionamento com clientes japoneses só aumentou.</p>',
                'text_en' => NULL,
                'image' => '1631723547.png',
                'publish' => 1,
                'created_at' => '2021-09-15 13:32:27',
                'updated_at' => '2021-09-15 13:34:01',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'year' => 1974,
                'title' => 'Novo escritório em Brasília',
                'title_en' => 'Novo escritório em Brasília',
                'text' => '<p>O escritório chega ao Planalto Central: inaugura sua mais nova sede, agora em Brasília, no Distrito Federal.</p>',
                'text_en' => NULL,
                'image' => '1631723587.png',
                'publish' => 1,
                'created_at' => '2021-09-15 13:33:07',
                'updated_at' => '2021-09-15 13:34:00',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'year' => 1978,
                'title' => '1ª sede fora do Brasil',
                'title_en' => '1ª sede fora do Brasil',
                'text' => '<p>Uma nova sede chega a Londres, Reino Unido, em uma associação com o advogado inglês John Anthony Clare até 2000.</p>',
                'text_en' => NULL,
                'image' => '1631723636.png',
                'publish' => 1,
                'created_at' => '2021-09-15 13:33:56',
                'updated_at' => '2021-09-15 13:33:59',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'year' => 1982,
                'title' => 'Ano marcado por inovação e incêndio no escritório',
                'title_en' => 'Ano marcado por inovação e incêndio no escritório',
                'text' => '<p>Pinheiro Neto Advogados implanta um sistema informatizado para acompanhar seus processos. Neste mesmo ano, o escritório da Rua Boa Vista é atingido por um incêndio. Felizmente, biblioteca e arquivo não são danificados.</p>',
                'text_en' => NULL,
                'image' => NULL,
                'publish' => 1,
                'created_at' => '2021-09-15 13:34:58',
                'updated_at' => '2021-09-15 13:35:43',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'year' => 1987,
                'title' => 'Encontro com a rainha Elizabeth II',
                'title_en' => 'Encontro com a rainha Elizabeth II',
                'text' => '<p>J.M. Pinheiro Neto recebe da rainha da Inglaterra Elizabeth II o título de Cavaleiro do Império Britânico.</p>',
                'text_en' => NULL,
                'image' => '1631723739.png',
                'publish' => 1,
                'created_at' => '2021-09-15 13:35:39',
                'updated_at' => '2021-09-15 13:42:06',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'year' => 1988,
                'title' => 'Visão do papel do advogado',
                'title_en' => 'Visão do papel do advogado',
                'text' => '<p>Quase 50 anos depois de ter fundado o escritório, Pinheiro Neto escreve a seus sócios a respeito de sua visão do papel do advogado.</p>',
                'text_en' => NULL,
                'image' => '1631723781.png',
                'publish' => 1,
                'created_at' => '2021-09-15 13:36:21',
                'updated_at' => '2021-09-15 13:42:07',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'year' => 1990,
                'title' => 'Plano de desenvolvimento para os profissionais',
                'title_en' => 'Plano de desenvolvimento para os profissionais',
                'text' => '<p>O escritório desenvolveu um minucioso plano de desenvolvimento dos advogados, que tem sido aprimorado com o passar dos anos.</p>',
                'text_en' => NULL,
                'image' => '1631723817.png',
                'publish' => 1,
                'created_at' => '2021-09-15 13:36:57',
                'updated_at' => '2021-09-15 13:42:07',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'year' => 1990,
                'title' => 'Capa da Revista Veja São Paulo',
                'title_en' => 'Capa da Revista Veja São Paulo',
            'text' => '<p>Revista Veja São Paulo (Ed. Abril) traz na capa reportagem sobre o escritório. Em 1991, a firma alcança mil clientes.</p>',
                'text_en' => NULL,
                'image' => '1631723858.png',
                'publish' => 1,
                'created_at' => '2021-09-15 13:37:38',
                'updated_at' => '2021-09-15 13:42:08',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'year' => 1992,
                'title' => 'Carta do Dr. Pinheiro',
                'title_en' => 'Carta do Dr. Pinheiro',
                'text' => '<p>J. M. Pinheiro Neto escreve uma carta aos sócios discutindo os rumos do escritório, mostrando os valores fundamentais que deveriam seguir após sua aposentadoria.</p>',
                'text_en' => NULL,
                'image' => '1631723902.png',
                'publish' => 1,
                'created_at' => '2021-09-15 13:38:22',
                'updated_at' => '2021-09-15 13:42:09',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'year' => 2000,
                'title' => 'Afastamento do Dr. Pinheiro',
                'title_en' => 'Afastamento do Dr. Pinheiro',
                'text' => '<p>Após quase seis décadas, J.M. Pinheiro Neto se afasta da presidência.</p>',
                'text_en' => NULL,
                'image' => '1631723989.png',
                'publish' => 1,
                'created_at' => '2021-09-15 13:39:49',
                'updated_at' => '2021-09-15 13:42:12',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'year' => 2002,
                'title' => 'Aniversário de 60 anos ',
                'title_en' => 'Aniversário de 60 anos ',
                'text' => '<p>Livro comemorativo de 60 anos do Escritório, escrito por Ignácio Loyola Brandão</p>',
                'text_en' => NULL,
                'image' => '1631724038.png',
                'publish' => 1,
                'created_at' => '2021-09-15 13:40:38',
                'updated_at' => '2021-09-15 13:42:14',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'year' => 2005,
                'title' => 'Comissão de Responsabilidade Social',
                'title_en' => 'Comissão de Responsabilidade Social',
                'text' => '<p>Criada a Comissão de Filantropia. Dois anos depois, ela é renomeada: Comissão de Responsabilidade Social.</p>',
                'text_en' => NULL,
                'image' => '1631724082.png',
                'publish' => 1,
                'created_at' => '2021-09-15 13:41:22',
                'updated_at' => '2021-09-15 13:42:15',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'year' => 2005,
                'title' => 'Falecimento do Dr. Pinheiro',
                'title_en' => 'Falecimento do Dr. Pinheiro',
                'text' => '<p>Em 21 de setembro, aos 88 anos, falece em São Paulo J. M. Pinheiro Neto.</p>',
                'text_en' => NULL,
                'image' => '1631724122.png',
                'publish' => 1,
                'created_at' => '2021-09-15 13:42:02',
                'updated_at' => '2021-09-15 13:42:16',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'year' => 2007,
                'title' => 'Escritório sustentável',
                'title_en' => 'Escritório sustentável',
                'text' => '<p>Primeiro escritório de advocacia brasileiro a neutralizar emissões de carbono.</p>',
                'text_en' => NULL,
                'image' => '1631724577.png',
                'publish' => 1,
                'created_at' => '2021-09-15 13:49:37',
                'updated_at' => '2021-09-15 13:51:43',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'year' => 2009,
                'title' => 'Comissão da Mulher',
                'title_en' => 'Comissão da Mulher',
                'text' => '<p>De forma pioneira, é criada a Comissão da Mulher, assegurando a multiplicidade de visões no escritório.</p>',
                'text_en' => NULL,
                'image' => '1631724615.png',
                'publish' => 1,
                'created_at' => '2021-09-15 13:50:15',
                'updated_at' => '2021-09-15 13:51:48',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'year' => 2009,
                'title' => 'Institucionalização do  Programa Pro Bono',
                'title_en' => 'Institucionalização do  Programa Pro Bono',
                'text' => '<p>Primeiro escritório de advocacia do País a remunerar os integrantes para casos gratuitos, institucionalizando o Programa Pro Bono.</p>',
                'text_en' => NULL,
                'image' => '1631724656.png',
                'publish' => 1,
                'created_at' => '2021-09-15 13:50:56',
                'updated_at' => '2021-09-15 13:51:49',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'year' => 2010,
                'title' => 'Um dos maiores investidores  sociais do Brasil',
                'title_en' => 'Um dos maiores investidores  sociais do Brasil',
            'text' => '<p>Pioneiro ao se juntar aos maiores investidores sociais do País, segundo Grupo de Institutos Fundações e Empresas (Gife).</p>',
                'text_en' => NULL,
                'image' => '1631724699.png',
                'publish' => 1,
                'created_at' => '2021-09-15 13:51:39',
                'updated_at' => '2021-09-15 13:51:51',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'year' => 2010,
                'title' => '1° relatório de atividades sociais',
                'title_en' => '1° relatório de atividades sociais',
                'text' => '<p>Lançamento do primeiro relatório de atividades sociais de Pinheiro Neto Advogados.</p>',
                'text_en' => NULL,
                'image' => '1631725387.png',
                'publish' => 1,
                'created_at' => '2021-09-15 14:03:07',
                'updated_at' => '2021-09-15 14:08:55',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'year' => 2011,
                'title' => 'Criação da Comissão da Diversidade e Inclusão',
                'title_en' => 'Criação da Comissão da Diversidade e Inclusão',
                'text' => '<p>Criada a Comissão da Diversidade e Inclusão para aprimorar boas práticas: menos desinformação, mais respeito, inclusão e dignidade.</p>',
                'text_en' => NULL,
                'image' => '1631725435.png',
                'publish' => 1,
                'created_at' => '2021-09-15 14:03:55',
                'updated_at' => '2021-09-15 14:08:56',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'year' => 2012,
                'title' => 'Nasce a Escola de Formação',
                'title_en' => 'Nasce a Escola de Formação',
                'text' => '<p>Criação da Escola de Formação Pinheiro Neto, desenvolvida para aprimorar a formação profissional dos advogados.</p>',
                'text_en' => NULL,
                'image' => '1631725484.png',
                'publish' => 1,
                'created_at' => '2021-09-15 14:04:44',
                'updated_at' => '2021-09-15 14:08:57',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'year' => 2012,
                'title' => 'Aniversário de 70 anos',
                'title_en' => 'Aniversário de 70 anos',
                'text' => '<p>Livro comemorativo de 70 anos do escritório, escrito por Mario Prata: Almanaque Pinheiro Neto, nossas sete décadas.</p>',
                'text_en' => NULL,
                'image' => '1631725523.png',
                'publish' => 1,
                'created_at' => '2021-09-15 14:05:23',
                'updated_at' => '2021-09-15 14:08:59',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'year' => 2012,
                'title' => 'Selo Paulista da Diversidade',
                'title_en' => 'Selo Paulista da Diversidade',
                'text' => '<p>O escritório recebe, da Secretaria do Emprego e Relações do Trabalho, o Selo Paulista da Diversidade na categoria Adesão.</p>',
                'text_en' => NULL,
                'image' => '1631725558.png',
                'publish' => 1,
                'created_at' => '2021-09-15 14:05:58',
                'updated_at' => '2021-09-15 14:09:00',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'year' => 2013,
                'title' => 'Prêmio Americas Women in  Business Law ',
                'title_en' => 'Prêmio Americas Women in  Business Law ',
                'text' => '<p>Euromoney concede o prêmio Americas Women in Business Law pelo melhor programa feminino de mentoria da América Latina.</p>',
                'text_en' => NULL,
                'image' => '1631725603.png',
                'publish' => 1,
                'created_at' => '2021-09-15 14:06:43',
                'updated_at' => '2021-09-15 14:09:02',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'year' => 2014,
                'title' => 'Serviços Jurídicos',
                'title_en' => 'Serviços Jurídicos',
            'text' => '<p>Nomeado o maior exportador de serviços jurídicos do País (Encontro Nacional de Comércio Exterior de Serviços).</p>',
                'text_en' => NULL,
                'image' => '1631725656.png',
                'publish' => 1,
                'created_at' => '2021-09-15 14:07:36',
                'updated_at' => '2021-09-15 14:09:04',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'year' => 2015,
                'title' => 'Acordo com Chevening',
                'title_en' => 'Acordo com Chevening',
                'text' => '<p>Pinheiro Neto Advogados anuncia acordo com o programa Chevening.</p>',
                'text_en' => NULL,
                'image' => '1631725696.png',
                'publish' => 1,
                'created_at' => '2021-09-15 14:08:16',
                'updated_at' => '2021-09-15 14:15:47',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'year' => 2016,
                'title' => 'Reconhecimento IFLR Americas Award',
                'title_en' => 'Reconhecimento IFLR Americas Award',
                'text' => '<p>Eleito o “escritório brasileiro do ano” no IFLR Americas Awards 2016.</p>',
                'text_en' => NULL,
                'image' => '1631725731.png',
                'publish' => 1,
                'created_at' => '2021-09-15 14:08:51',
                'updated_at' => '2021-09-15 14:15:48',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'year' => 2016,
                'title' => 'Certificação LEED',
                'title_en' => 'Certificação LEED',
            'text' => '<p>Recebe a certificação Leadership in Energy and Environmental Design (LEED), de edifício que atende critérios de racionalização de recursos naturais.</p>',
                'text_en' => NULL,
                'image' => '1631725796.png',
                'publish' => 1,
                'created_at' => '2021-09-15 14:09:56',
                'updated_at' => '2021-09-15 14:15:49',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'year' => 2017,
                'title' => 'Único escritório latino a integrar  ao Stanford Program Law',
                'title_en' => 'Único escritório latino a integrar  ao Stanford Program Law',
                'text' => '<p>Único escritório da América Latina a integrar o Stanford Program in Law, Science and Technology da Stanford Law School.</p>',
                'text_en' => NULL,
                'image' => '1631725833.png',
                'publish' => 1,
                'created_at' => '2021-09-15 14:10:33',
                'updated_at' => '2021-09-15 14:15:51',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'year' => 2017,
                'title' => 'Aniversário de 75 anos',
                'title_en' => 'Aniversário de 75 anos',
                'text' => '<p>Celebração de seus 75 anos com o patrocínio da exposição de obras do pintor francês Henri de Toulouse-Lautrec no MASP.</p>',
                'text_en' => NULL,
                'image' => '1631725874.png',
                'publish' => 1,
                'created_at' => '2021-09-15 14:11:14',
                'updated_at' => '2021-09-15 14:15:52',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'year' => 2018,
                'title' => 'Nova sede na Califórnia',
                'title_en' => 'Nova sede na Califórnia',
                'text' => '<p>Abertura do escritório em Palo Alto e consolidação como a firma brasileira com maior representatividade no Vale do Silício, EUA.</p>',
                'text_en' => NULL,
                'image' => '1631725906.png',
                'publish' => 1,
                'created_at' => '2021-09-15 14:11:46',
                'updated_at' => '2021-09-15 14:15:54',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'year' => 2018,
                'title' => 'Selo de Direitos Humanos',
                'title_en' => 'Selo de Direitos Humanos',
                'text' => '<p>Recebe pela primeira vez o Selo de Direitos Humanos da Prefeitura de São Paulo.</p>',
                'text_en' => NULL,
                'image' => '1631725943.png',
                'publish' => 1,
                'created_at' => '2021-09-15 14:12:23',
                'updated_at' => '2021-09-15 14:15:55',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'year' => 2019,
                'title' => 'Reconhecimento inédito',
                'title_en' => 'Reconhecimento inédito',
                'text' => '<p>De forma inédita, o Chambers Latin America Awards 2019 concede a uma única firma os dois principais prêmios: melhor escritório do Brasil e da América Latina.</p>',
                'text_en' => NULL,
                'image' => '1631725983.png',
                'publish' => 1,
                'created_at' => '2021-09-15 14:13:03',
                'updated_at' => '2021-09-15 14:15:57',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'year' => 2019,
                'title' => 'Equidade racial',
                'title_en' => 'Equidade racial',
                'text' => '<p>Pinheiro Neto Advogados participa da Aliança Jurídica pela Equidade Racial.</p>',
                'text_en' => NULL,
                'image' => '1631726020.png',
                'publish' => 1,
                'created_at' => '2021-09-15 14:13:40',
                'updated_at' => '2021-09-15 14:15:58',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'year' => 2020,
                'title' => 'Nova sede em Tóquio',
                'title_en' => 'Nova sede em Tóquio',
                'text' => '<p>Inauguração do escritório em Tóquio, no Japão, para funcionar como o hub asiático da firma.</p>',
                'text_en' => NULL,
                'image' => '1631726057.png',
                'publish' => 1,
                'created_at' => '2021-09-15 14:14:17',
                'updated_at' => '2021-09-15 14:16:00',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'year' => 2020,
                'title' => 'Site mais acessível',
                'title_en' => 'Site mais acessível',
                'text' => '<p>Em celebração ao mês da visibilidade da Comunidade Surda Brasileira, conhecido como Setembro Azul, site torna-se mais acessível com tradutor para Libras e leitor de site.</p>',
                'text_en' => NULL,
                'image' => '1631726093.png',
                'publish' => 1,
                'created_at' => '2021-09-15 14:14:53',
                'updated_at' => '2021-09-15 14:16:04',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'year' => 2021,
                'title' => 'Compensação de carbono',
                'title_en' => 'Compensação de carbono',
                'text' => '<p>15 anos de compensação de carbono.</p>',
                'text_en' => NULL,
                'image' => '1631726143.png',
                'publish' => 1,
                'created_at' => '2021-09-15 14:15:43',
                'updated_at' => '2021-09-15 14:16:05',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}